#!/bin/bash
# Sets default values for the script.
KVMBLDR_DEF_DISKDIR=/disks/compute/KVM
KVMBLDR_DEF_ISODIR=/disks/raid/storage/iso
KVMBLDR_DEF_WINISO=windows10_21h2.iso
KVMBLDR_DEF_WINVIRTISO=virtio-win-0.1.229.iso
KVMBLDR_DEF_LNXISO=debian-12.4.0-amd64-netinst.iso
KVMBLDR_DEF_WINDISKSZ=64
KVMBLDR_DEF_LNXDISKSZ=32
KVMBLDR_DEF_VMNETW=enp37s0.br16
KVMBLDR_DEF_VMSIZE=aa


# DO NOT TOUCH
KVMBLDR_DEF_WINISODIR=$KVMBLDR_DEF_ISODIR/$KVMBLDR_DEF_WINISO
KVMBLDR_DEF_WINVIRTISODIR=$KVMBLDR_DEF_ISODIR/$KVMBLDR_DEF_WINVIRTISO
KVMBLDR_DEF_LNXISODIR=$KVMBLDR_DEF_ISODIR/$KVMBLDR_DEF_LNXISO

# Func to check if default needs to be used
setdef(){
    ARG=$1
    DEF=$2
    if [[ -z $ARG ]]; then
      echo $DEF
    else
      echo $ARG
    fi
}